### ISSUE TITLE
Sistema de Respawn

### ISSUE THREAD

**Issue by Cundalf** [Cundalf/ALT_CUN_W40K#3]
Desarrollar un Respawn Controller el cual gestione distintos Game Objects que sirvan como punto de respawn físico.
La forma de respawn debería ser totalmente configurable desde el editor, se debería cumplir con lo siguientes casos:

1. Respawn aleatorio entre todos los puntos cada cierto tiempo.
2. Respawn aleatorio entre todos los puntos de X cantidad de enemigos.
3. Punto 1 y 2 combinados.
4. Respawn en un solo punto de enemigos cada cierto tiempo
5. Respawn en un solo punto de enemigos de X cantidad de enemigos.
6. Punto 5 y 6 combinados.
7. El respawn elegido en el punto 4 y 5 pueda rotar bajo ciertas condiciones (tiempo o por algún método)
8. Considerar distintos tipos de enemigos. 

Tip:
Se podría desarrollar testeando con un game object que se autodestruya cada X cantidad de tiempo.

**Comment by AgustinAllamanoCosta** [comment]
No puedo hacer que los puntos roten y al mismo tiempo sean elegidos de manera aleatorio. Mas adelante voy a refactorizar el administrador en variso objetos con responsabilidades mas simples para aislar los problemas.
