### ISSUE TITLE
Administrador de vida

### ISSUE THREAD

**Issue by Cundalf** [Cundalf/ALT_CUN_W40K#5]
Desarrollar un sistema generico que se aplicable a toda entidad que pueda morir (player, enemigos, obstaculos, objetivos, etc).

Debe contar con:

- Vida Inicial (modificable desde el editor).
- Vida Maxima (modificable desde el editor).
- Vida Actual (con su Setter & Getter)

Recordar mantener todo bien encapsulado.

**Comment by AgustinAllamanoCosta** [comment]
@Cundalf Tiene sentido poner validaciones para que la vida no sea negativa ? estoy pensando que podria se util en algunos casos

**Comment by AgustinAllamanoCosta** [comment]
Otro tema, el administrador tiene la responsabilidad de que cuando la vida alcanza el 0 la entidad que tiene el administrador desaparece ? @Cundalf

**Comment by AgustinAllamanoCosta** [comment]
El administrador si tiene la responsabilidad de destruir el objeto de acuerdo al tag, se desarrolla en el issues #7

**Comment by Cundalf** [comment]
@AgustinAllamanoCosta No leí la implementación aun pero me parece que si tiene sentido que el administrador destruya el game object. Capaz podemos ver de ponerlo parametrizable desde el editor con un booleano (si es que ya no lo hiciste), lo evaluamos según la necesidad que surja. En cuanto a la vida no pueda ser negativa creo que por ahora es indiferente, si la vida es menor o igual a cero la entidad en cuestión esta muerta. Pero si ves algo que yo no, no esta mal que quede en cero, yo lo validaría en el setter que si es menor a 0 fuerce el cero.
