### ISSUE TITLE
Muerte de enemigos

### ISSUE THREAD

**Issue by Cundalf** [Cundalf/ALT_CUN_W40K#7]
En el administrador de vida desarrollado en la issue #5 desarrollar que cuando la vida actual sea igual o menor a 0 realice una acción dependiendo del tag del GO que contenga el script.

Si es el player, notificara a un administrador del juego.
Si es enemigo, notificara al administrador de oleadas.

En el futuro se agregaran obstáculos.

**Comment by AgustinAllamanoCosta** [comment]
Se crear los test necesarios para probar todas los casos que aparecen en el issues. Ademas de crear escenas basicas para poder ejecutar los mismos, se da el issues como terminado gracias a que todas las pruebas pasan exitosamente.
