### ISSUE TITLE
Administrador del juego

### ISSUE THREAD

**Issue by Cundalf** [Cundalf/ALT_CUN_W40K#8]
Desarrollar un script llamado "GameManager" (en ingles para que el motor lo identifique como tal). El cual tendrá varios métodos con las siguientes implementaciones:

- Pausar el juego.
- Finalizar el juego.
- Gestionar el "Game Over".
- Gestionar la victoria.
- Gestionar el estado actual del juego con un enumerador (JUGANDO, PAUSA, EN MENU, etc...)

**Comment by AgustinAllamanoCosta** [comment]
Se termino con el desarrollo para los estados del administrador del juego junto con sus test.
